cmake_minimum_required(VERSION 3.12)

macro(get_version project_name)
    execute_process(COMMAND "git" "describe" WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} OUTPUT_VARIABLE version_string RESULT_VARIABLE result)

    if (result EQUAL 0)
        string(FIND ${version_string} "-" dash_idx)
        if (NOT dash_idx EQUAL -1)
            string(SUBSTRING ${version_string} 0 ${dash_idx} version_string)
        endif()
        string(STRIP ${version_string} version_string)
        message(STATUS "Version number was extracted from git: ${version_string}.")
        string(REGEX MATCHALL "[0-9]+" version_list ${version_string})
        list(GET version_list 0 ${project_name}_VERSION_MAJOR)
        list(GET version_list 1 ${project_name}_VERSION_MINOR)
        list(GET version_list 2 ${project_name}_VERSION_PATCH)
    else()
        set(${project_name}_VERSION_MAJOR 0)
        set(${project_name}_VERSION_MINOR 1)
        set(${project_name}_VERSION_PATCH 0)
        set(version_string "${${project_name}_VERSION_MAJOR}.${${project_name}_VERSION_MINOR}.${${project_name}_VERSION_PATCH}")
        message(STATUS "Version could not be extracted from git. Using version number from Cmake: ${version_string}.")
    endif()

    set(${project_name}_VERSION ${version_string})
endmacro(get_version)
